// const premTeams = {
//   arsenal: 'Arsenal',
//   astonVilla: 'Aston Villa',
//   bournmouth: 'AFC Bournmouth',
//   brighton: 'Brighton',
//   burnley: 'Burnley',
//   chelsea: 'Chelsea',
//   crystalPalace: 'Crystal Palace',
//   everton: 'Everton',
//   leicester: 'Leicester City',
//   liverpool: 'Liverpool',
//   manCity: 'Manchester City',
//   manUnited: 'Manchester United',
//   newcastle: 'Newcastle United',
//   norwich: 'Norwich City',
//   sheffield: 'Sheffield United',
//   southampton: 'Southampton',
//   tottenham: 'Tottenham Hotspurs',
//   watford: 'Watford',
//   westham: 'West Ham United',
//   wolves: 'Wolverhampton Wanderers',
// };

const premTeams = [
  'Arsenal',
  'Aston Villa',
  'AFC Bournmouth',
  'Brighton',
  'Burnley',
  'Chelsea',
  'Crystal Palace',
  'Everton',
  'Leicester City',
  'Liverpool',
  'Manchester City',
  'Manchester United',
  'Newcastle United',
  'Norwich City',
  'Sheffield United',
  'Southampton',
  'Tottenham Hotspurs',
  'Watford',
  'West Ham United',
  'Wolverhampton Wanderers',
];

export default premTeams;
